package com.datein.date_in;

public interface Constants {

	// Google cloud messaging related.
	String SENDER_ID = "994318371798";
	int PLAY_SERVICES_RESOLUTION_REQUEST = 9000;
	long GCM_DEFAULT_TTL = 2 * 60; // two minutes
	String REGISTRATION_ID = "REGISTRATION_ID";
	String ACTION = "ACTION";

	// Other constants.
	String KEY_LOGGED_IN = "KEY_LOGGED_IN";
	String KEY_REG_ID = "KEY_REG_ID";
	String KEY_MSG_ID = "KEY_MSG_ID";
	String KEY_APP_VERSION = "KEY_APP_VERSION";
	String PACKAGE = "com.datein.date_in.gcm";
	String KEY_MESSAGE_TXT = "KEY_MESSAGE_TXT";

	/**
	 * All the state.
	 */
	String STATE_START = "STATE_START";

	// Login related state.
	String STATE_LOGIN = "STATE_LOGIN";
	String STATE_LOGGING_IN = "STATE_LOGGING_IN";
	String STATE_LOGIN_OK = "STATE_LOGIN_OK";
	String STATE_LOGIN_FAIL = "STATE_LOGIN_FAIL";

	// Register related state.
	String STATE_REGISTER = "STATE_REGISTER";
	String STATE_REGISTERING = "STATE_REGISTERING";
	String STATE_REGISTER_OK = "STATE_REGISTER_OK";
	String STATE_EMAIL_TAKEN = "STATE_EMAIL_TAKEN";
	String STATE_DISPLAY_NAME_TAKEN = "STATE_DISPLAY_NAME_TAKEN";

	// Main related state.
	String STATE_MAIN = "STATE_MAIN";
	String STATE_MAIN_DRAWER_OPEN = "STATE_MAIN_DRAWER_OPEN";
	String STATE_MAIN_DRAWER_CLOSE = "STATE_MAIN_DRAWER_CLOSE";

	// Calendar related state.
	String STATE_CALENDAR = "STATE_CALENDAR";
	String STATE_CALENDAR_REQUESTING = "STATE_CALENDAR_REQUESTING";
	String STATE_CALENDAR_OK = "STATE_CALENDAR_OK";
	String STATE_CALENDAR_FAIL = "STATE_CALENDAR_FAIL";

	// Friends related state.
	String STATE_FRIENDS = "STATE_FRIENDS";
	String STATE_FRIENDS_SEARCHING = "STATE_FRIENDS_SEARCHING";
	String STATE_FRIENDS_SEARCH_OK = "STATE_FRIENDS_SEARCH_OK";
	String STATE_FRIENDS_SEARCH_FAIL = "STATE_FRIENDS_SEARCH_FAIL";
	String STATE_FRIENDS_ADDING = "STATE_FRIENDS_ADDING";
	String STATE_FRIENDS_ADD_OK = "STATE_FRIENDS_ADD_OK";
	String STATE_FRIENDS_ADD_FAIL = "STATE_FRIENDS_ADD_FAIL";
	String STATE_FRIENDS_ACCEPTING = "STATE_FRIENDS_ACCEPTING";
	String STATE_FRIENDS_ACCEPT_OK = "STATE_FRIENDS_ACCEPT_OK";
	String STATE_FRIENDS_ACCEPT_FAIL = "STATE_FRIENDS_ACCEPT_FAIL";
	String STATE_FRIENDS_REJECTING = "STATE_FRIENDS_REJECTING";
	String STATE_FRIENDS_REJECT_OK = "STATE_FRIENDS_REJECT_OK";
	String STATE_FRIENDS_REJECT_FAIL = "STATE_FRIENDS_REJECT_FAIL";
	String STATE_FRIENDS_LIST_REQUESTING = "STATE_FRIENDS_LIST_REQUESTING";
	String STATE_FRIENDS_LIST_OK = "STATE_FRIENDS_LIST_OK";
	String STATE_FRIENDS_LIST_FAIL = "STATE_FRIENDS_LIST_FAIL";

	// Event related state.
	String STATE_EVENTS = "STATE_EVENTS";
	String STATE_EVENTS_REQUEST_COMMON_TIME = "STATE_EVENTS_REQUEST_COMMON_TIME";
	String STATE_EVENTS_REQUEST_COMMON_TIME_OK = "STATE_EVENTS_REQUEST_COMMON_TIME_OK";
	String STATE_EVENTS_REQUEST_COMMON_TIME_FAIL = "STATE_EVENTS_REQUEST_COMMON_TIME_FAIL";
	String STATE_EVENTS_CREATING = "STATE_EVENTS_CREATING";
	String STATE_EVENTS_CREATE_OK = "STATE_EVENTS_CREATE_OK";
	String STATE_EVENTS_CREATE_FAIL = "STATE_EVENTS_CREATE_FAIL";


	String STATE_EDIT_CALENDAR_SYNCING = "STATE_EDIT_CALENDAR_SYNCING";
	String STATE_EDIT_CALENDAR_SYNC_OK = "STATE_EDIT_CALENDAR_SYNC_OK";
	String STATE_EDIT_CALENDAR_SYNC_FAIL = "STATE_EDIT_CALENDAR_SYNC_FAIL";

	/**
	 * All the send actions.
	 */
	String ACTION_REGISTER = PACKAGE + ".REGISTER";
	String ACTION_UNREGISTER = PACKAGE + ".UNREGISTER";
	String ACTION_LOGIN = PACKAGE + ".LOGIN";
	String ACTION_SEARCH = PACKAGE + ".SEARCH";
	String ACTION_FRIEND_ADD = PACKAGE + ".FRIEND_ADD";
	String ACTION_FRIEND_ACCEPT = PACKAGE + ".FRIEND_ACCEPT";
	String ACTION_FRIEND_REJECT = PACKAGE + ".FRIEND_REJECT";
	String ACTION_FRIEND_UNDO_IGNORE = PACKAGE + ".FRIEND_UNDO_IGNORE";
	String ACTION_FRIEND = PACKAGE + ".FRIEND";
	String ACTION_CALENDAR = PACKAGE + ".CALENDAR";
	String ACTION_EDIT_CALENDAR = PACKAGE + ".EDIT_CALENDAR";
	String ACTION_EVENT_REQUEST = PACKAGE + ".EVENT_REQUEST";
	String ACTION_EVENT_CREATE = PACKAGE + ".EVENT_CREATE";
	String ACTION_EDIT_CALENDAR_GET = PACKAGE + ".EDIT_CALENDAR_GET";
	String ACTION_ECHO = PACKAGE + ".ECHO";
	String ACTION_NOTIFICATION_REQUEST = PACKAGE + ".NOTIFICATION_REQUEST";

	/**
	 * All the receive actions.
	 */
	String ACTION_LOGIN_OK = PACKAGE + ".LOGIN_OK";
	String ACTION_LOGIN_FAIL = PACKAGE + ".LOGIN_FAIL";
	String ACTION_REGISTER_OK = PACKAGE + ".REGISTER_OK";
	String ACTION_REGISTER_EMAIL_TAKEN = PACKAGE + ".REGISTER_EMAIL_TAKEN";
	String ACTION_REGISTER_DISPLAY_NAME_TAKEN = PACKAGE + ".REGISTER_DISPLAY_NAME_TAKEN";
	String ACTION_FRIEND_SEARCH_OK = PACKAGE + ".FRIEND_SEARCH_OK";
	String ACTION_FRIEND_SEARCH_FAIL = PACKAGE + ".FRIEND_SEARCH_FAIL";
	String ACTION_FRIEND_ADD_OK = PACKAGE + ".FRIEND_ADD_OK";
	String ACTION_FRIEND_ADD_FAIL = PACKAGE + ".FRIEND_ADD_FAIL";
	String ACTION_FRIEND_ACCEPT_OK = PACKAGE + ".FRIEND_ACCEPT_OK";
	String ACTION_FRIEND_ACCEPT_FAIL = PACKAGE + ".FRIEND_ACCEPT_FAIL";
	String ACTION_FRIEND_REJECT_OK = PACKAGE + ".FRIEND_REJECT_OK";
	String ACTION_FRIEND_REJECT_FAIL = PACKAGE + ".FRIEND_REJECT_FAIL";
	String ACTION_FRIEND_OK = PACKAGE + ".FRIEND_OK";
	String ACTION_FRIEND_FAIL = PACKAGE + ".FRIEND_FAIL";
	String ACTION_FRIEND_REQUEST = PACKAGE + ".FRIEND_REQUEST";
	String ACTION_FRIEND_ACCEPTED = PACKAGE + ".FRIEND_ACCEPTED";
	String ACTION_EDIT_CALENDAR_SYNC_OK = PACKAGE + ".EDIT_CALENDAR_SYNC_OK";
	String ACTION_EDIT_CALENDAR_SYNC_FAIL = PACKAGE + ".EDIT_CALENDAR_SYNC_FAIL";
	String ACTION_CALENDAR_OK = PACKAGE + ".CALENDAR_OK";
	String ACTION_CALENDAR_FAIL = PACKAGE + ".CALENDAR_FAIL";
	String ACTION_EVENT_REQUEST_OK = PACKAGE + ".EVENT_REQUEST_OK";
	String ACTION_EVENT_REQUEST_FAIL = PACKAGE + ".EVENT_REQUEST_FAIL";
	String ACTION_EVENT_CREATE_OK = PACKAGE + ".EVENT_CREATE_OK";
	String ACTION_EVENT_CREATE_FAIL = PACKAGE + ".EVENT_CREATE_FAIL";
}
